# Generated by Django 2.2.7 on 2019-11-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msim', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_mid',
        ),
    ]
