# Generated by Django 2.2.7 on 2019-11-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msim', '0003_remove_contact_contact_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='handle',
            field=models.TextField(default='invalid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='servername',
            field=models.TextField(default='invalid'),
            preserve_default=False,
        ),
    ]
