# Generated by Django 2.2.7 on 2019-11-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msim', '0004_auto_20191128_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='caption',
            field=models.TextField(default='Contact'),
            preserve_default=False,
        ),
    ]
