# Generated by Django 3.0.2 on 2020-01-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msim', '0005_contact_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_mid', models.TextField()),
                ('recipient_mid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author_mid', models.TextField()),
                ('text', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msim.PrivateChat')),
                ('prev_msg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msim.PrivateChatMessage')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChatReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_mid', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msim.PrivateChat')),
                ('last_read_msg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='msim.PrivateChatMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msim.User')),
            ],
        ),
    ]
