# Generated by Django 3.0.2 on 2020-01-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msim', '0007_auto_20200108_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatechatmessage',
            old_name='prev_msg_id',
            new_name='prev_msg',
        ),
    ]
